# Generated by Django 5.2.17 on 2026-09-27 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('coach', 'Coach app'), ('athlete', 'Athlete app')], max_length=10)),
                ('description', models.TextField()),
                ('page', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('screen', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('seen', 'Seen'), ('fixed', 'Fixed'), ('wontfix', "Won't fix")], default='new', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.gym')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('issue', 'Issue reported'), ('message', 'Message'), ('pr', 'PR'), ('program_ending', 'Program running out'), ('metrics_missing', 'Missing metrics'), ('missed', 'Missed session'), ('video', 'Form video'), ('week_published', 'Week published')], max_length=20)),
                ('dedupe_key', models.CharField(max_length=80)),
                ('text', models.CharField(max_length=300)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.athlete')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(condition=models.Q(('cleared_at__isnull', True)), fields=['recipient', '-created_at'], name='feed_by_recipient')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'athlete', 'kind', 'dedupe_key'), name='one_notification_per_key', nulls_distinct=False)],
            },
        ),
    ]
