# Generated by Django 5.2.17 on 2026-09-27 00:33

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.gym')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.gym')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, help_text="Marks exercises that came from the starter library (e.g. 'sn'), so the library can be refreshed without duplicates. Blank for exercises a coach creates. Nothing else may depend on it: features use the gym's own settings, e.g. TrackedLift.", max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('measure', models.CharField(choices=[('reps', 'Reps'), ('time', 'Time'), ('distance', 'Distance')], default='reps', max_length=10)),
                ('reps_per_rep', models.PositiveSmallIntegerField(default=1, help_text='2 for a "1+1" complex')),
                ('youtube_url', models.URLField(blank=True)),
                ('cue', models.TextField(blank=True)),
                ('warmup', models.BooleanField(default=False, help_text='A warm-up drill: added to sessions as part of the warm-up checklist.')),
                ('archived', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='exercises.category')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='accounts.gym')),
                ('percent_of', models.ForeignKey(blank=True, help_text="The max percentages are worked from. Empty means this exercise's own max.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.exercise')),
                ('tags', models.ManyToManyField(blank=True, related_name='exercises', to='exercises.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackedLift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_by', to='exercises.exercise')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_lifts', to='accounts.gym')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('gym'), name='unique_category_name_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('gym'), name='unique_tag_name_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('gym'), name='unique_exercise_name_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('key', ''), _negated=True), fields=('gym', 'key'), name='unique_exercise_key_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='trackedlift',
            constraint=models.UniqueConstraint(fields=('gym', 'exercise'), name='unique_tracked_lift_per_gym'),
        ),
    ]
