# Generated by Django 5.2.17 on 2026-09-27 16:24

from django.db import migrations, models

import apps.sync.triggers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("exercises", "0001_initial"),
        ("programs", "0001_initial"),
        ("library", "0002_initial"),
        ("workouts", "0001_initial"),
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('txid', models.BigIntegerField(db_index=True)),
                ('table', models.CharField(max_length=63)),
                ('row_id', models.UUIDField()),
                ('op', models.CharField(choices=[('I', 'Insert'), ('U', 'Update'), ('D', 'Delete')], max_length=1)),
                ('athlete_id', models.UUIDField(db_index=True, null=True)),
                ('gym_id', models.UUIDField(db_index=True, null=True)),
                ('at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['athlete_id', 'txid'], name='change_by_athlete'), models.Index(fields=['gym_id', 'txid'], name='change_by_gym')],
            },
        ),
        migrations.RunPython(apps.sync.triggers.install, apps.sync.triggers.uninstall),
    ]
