# Generated by Django 5.2.17 on 2026-09-27 00:41

import apps.programs.models
import django.db.models.constraints
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('exercises', '0001_initial'),
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=80)),
                ('emoji', models.CharField(default='🍎', max_length=8)),
                ('cadence', models.CharField(choices=[('daily', 'Every day'), ('training', 'Training days'), ('3x', '3× a week'), ('5x', '5× a week')], default='daily', max_length=10)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habits', to='accounts.athlete')),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='library.template')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('start_date', models.DateField()),
                ('note', models.TextField(blank=True, help_text='Goal, rest, nutrition: shown to the athlete.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='accounts.athlete')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='library.template')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='programs.programday')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('rep_scheme', models.CharField(blank=True, max_length=60)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('load_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('load_basis', models.CharField(choices=[('percent', '% of max'), ('rpe', 'RPE'), ('weight', 'Weight'), ('bodyweight', 'Bodyweight'), ('none', 'No load')], default='none', max_length=12)),
                ('rir', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rir_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('custom_fields', models.JSONField(blank=True, default=list)),
                ('warmup', models.BooleanField(default=False)),
                ('section', models.CharField(blank=True, max_length=40)),
                ('section_note', models.CharField(blank=True, max_length=200)),
                ('superset', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='exercises.exercise')),
                ('tag_slot_tags', models.ManyToManyField(blank=True, related_name='+', to='exercises.tag')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='programs.programsession')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('focus_note', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='programs.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='programday',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.programweek'),
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='programs.programweek')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WeekType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('colour', models.CharField(max_length=7, validators=[apps.programs.models.validate_colour])),
                ('order', models.PositiveIntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_types', to='accounts.gym')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='programweek',
            name='week_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_weeks', to='programs.weektype'),
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='programs.habit')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('habit', 'date'), name='one_log_per_habit_day')],
            },
        ),
        migrations.CreateModel(
            name='PrescribedSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('set_number', models.PositiveSmallIntegerField()),
                ('rep_scheme', models.CharField(blank=True, max_length=30)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('load_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_overrides', to='programs.prescription')),
            ],
            options={
                'ordering': ['set_number'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('set_number__gte', 1)), name='prescribedset_set_number_from_1'), models.CheckConstraint(condition=models.Q(('load_value__isnull', True), ('load_value__gte', 0), _connector='OR'), name='prescribedset_load_not_negative'), models.UniqueConstraint(fields=('prescription', 'set_number'), name='unique_set_per_prescription')],
            },
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('athlete',), name='one_active_program_per_athlete'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(('sets__gte', 1)), name='prescription_sets_at_least_1'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(('rir_max__isnull', True), models.Q(('rir__isnull', False), ('rir_max__gte', models.F('rir'))), _connector='OR'), name='prescription_rir_range_in_order'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(('load_value__isnull', True), ('load_value__gte', 0), _connector='OR'), name='prescription_load_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('load_basis', 'percent'), _negated=True), ('load_value__isnull', True), ('load_value__range', (1, 200)), _connector='OR'), name='prescription_percent_1_to_200'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('load_basis', 'rpe'), _negated=True), ('load_value__isnull', True), ('load_value__range', (1, 10)), _connector='OR'), name='prescription_rpe_1_to_10'),
        ),
        migrations.AddConstraint(
            model_name='programday',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('week', 'date'), name='unique_day_per_week'),
        ),
        migrations.AddConstraint(
            model_name='weektype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('gym'), name='unique_week_type_name_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='programweek',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('program', 'order'), name='unique_week_order_per_program'),
        ),
    ]
