# Generated by Django 5.2.17 on 2026-09-27 00:52

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('units', models.CharField(choices=[('kg', 'kilograms'), ('lb', 'pounds')], default='kg', max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=64, validators=[apps.accounts.models.validate_timezone])),
                ('week_start', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (6, 'Sunday')], default=0, help_text='The day training weeks start on (Python weekday: 0 = Monday, 6 = Sunday).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaxEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reps', models.PositiveSmallIntegerField(default=1)),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('athlete', 'Athlete'), ('coach', 'Coach'), ('session', 'Session')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'max entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('timezone', models.CharField(default='UTC', max_length=64, validators=[apps.accounts.models.validate_timezone])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('weight_class', models.CharField(blank=True, max_length=20)),
                ('competition_name', models.CharField(blank=True, max_length=120)),
                ('competition_date', models.DateField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('years_training', models.CharField(blank=True, choices=[('<1', '< 1'), ('1-3', '1–3'), ('3-5', '3–5'), ('5+', '5+')], max_length=4)),
                ('units', models.CharField(choices=[('kg', 'kilograms'), ('lb', 'pounds')], default='kg', max_length=2)),
                ('max_updates', models.CharField(choices=[('approve', 'Coach approves'), ('auto', 'Automatically')], default='approve', help_text='When a session beats a working max: update it straight away, or wait for the coach.', max_length=8)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hide_history_before_link', models.BooleanField(default=False, help_text='A new coach sees only training from the day their coaching link started.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__name'],
            },
        ),
        migrations.CreateModel(
            name='BodyweightEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('athlete', 'Athlete'), ('coach', 'Coach'), ('session', 'Session')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodyweights', to='accounts.athlete')),
            ],
            options={
                'verbose_name_plural': 'bodyweight entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='Head coach', max_length=60)),
                ('digest', models.BooleanField(default=True, help_text='Email a morning digest of new attention items.')),
                ('last_digest_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coachings', to='accounts.athlete')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coachings', to='accounts.coach')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coachings', to='accounts.gym')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GymMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('coach', 'Coach')], default='coach', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.coach')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.gym')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('token', models.CharField(default=apps.accounts.models.new_invite_token, editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models.default_invite_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='accounts.coach')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='accounts.gym')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
