# Generated by Django 5.2.17 on 2026-09-27 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('exercises', '0001_initial'),
        ('library', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='starting_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='library.template'),
        ),
        migrations.AddField(
            model_name='maxentry',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxes', to='accounts.athlete'),
        ),
        migrations.AddField(
            model_name='maxentry',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='max_entries', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='maxentry',
            name='set_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='max_entries', to='workouts.setlog'),
        ),
        migrations.AddConstraint(
            model_name='bodyweightentry',
            constraint=models.CheckConstraint(condition=models.Q(('kg__gt', 0)), name='bodyweight_positive'),
        ),
        migrations.AddConstraint(
            model_name='maxentry',
            constraint=models.CheckConstraint(condition=models.Q(('kg__gt', 0)), name='max_positive'),
        ),
    ]
