# Generated by Django 5.2.17 on 2026-09-27 00:33

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('exercises', '0001_initial'),
        ('library', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='starting_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='library.template'),
        ),
        migrations.AddField(
            model_name='maxentry',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maxes', to='accounts.athlete'),
        ),
        migrations.AddField(
            model_name='maxentry',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='max_entries', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='maxentry',
            name='set_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='max_entries', to='workouts.setlog'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_email_any_case'),
        ),
        migrations.AddIndex(
            model_name='bodyweightentry',
            index=models.Index(fields=['athlete', '-date'], name='bodyweight_by_athlete_date'),
        ),
        migrations.AddConstraint(
            model_name='bodyweightentry',
            constraint=models.CheckConstraint(condition=models.Q(('kg__gt', 0)), name='bodyweight_positive'),
        ),
        migrations.AddIndex(
            model_name='maxentry',
            index=models.Index(fields=['athlete', 'exercise', '-date'], name='max_by_athlete_exercise_date'),
        ),
        migrations.AddConstraint(
            model_name='maxentry',
            constraint=models.CheckConstraint(condition=models.Q(('kg__gt', 0)), name='max_positive'),
        ),
    ]
