# Generated by Django 5.2.17 on 2026-09-27 00:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('exercises', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('scale', '1–10 scale'), ('choice', 'Multiple choice'), ('text', 'Short answer')], max_length=10)),
                ('text', models.CharField(max_length=200)),
                ('low_label', models.CharField(blank=True, max_length=60)),
                ('high_label', models.CharField(blank=True, max_length=60)),
                ('options', models.JSONField(blank=True, default=list)),
                ('detail_label', models.CharField(blank=True, max_length=60)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.athlete')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_questions', to='accounts.gym')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checkin_skipped', models.BooleanField(default=False)),
                ('session_rpe', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_logs', to='accounts.athlete')),
                ('program_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='programs.programsession')),
                ('week_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_logs', to='programs.weektype')),
            ],
            options={
                'ordering': ['-date', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('prescribed', models.JSONField(blank=True, default=dict)),
                ('warmup', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.athlete')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_exercises', to='exercises.exercise')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged', to='programs.prescription')),
                ('session_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.sessionlog')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('pain', 'Pain / possible injury'), ('equipment', 'Equipment not available'), ('prescription', 'Prescription looks wrong'), ('other', 'Something else')], max_length=14)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='accounts.athlete')),
                ('session_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='workouts.sessionlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=120)),
                ('key', models.CharField(max_length=300, unique=True)),
                ('content_type', models.CharField(max_length=60)),
                ('size', models.PositiveBigIntegerField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.athlete')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='workouts.sessionexercise')),
                ('session_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='workouts.sessionlog')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CheckinAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question_text', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('scale', '1–10 scale'), ('choice', 'Multiple choice'), ('text', 'Short answer')], max_length=10)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('other_text', models.TextField(blank=True)),
                ('athlete', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.athlete')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='workouts.checkinquestion')),
                ('session_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='workouts.sessionlog')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('set_number', models.PositiveSmallIntegerField()),
                ('load_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rir', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now=True)),
                ('max_dismissed', models.BooleanField(default=False)),
                ('athlete', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.athlete')),
                ('session_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.sessionexercise')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='checkinquestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('athlete__isnull', True), ('gym__isnull', False)), models.Q(('athlete__isnull', False), ('gym__isnull', True)), _connector='OR'), name='checkin_question_has_exactly_one_owner'),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['athlete', '-date', '-started_at'], name='session_log_by_athlete_date'),
        ),
        migrations.AddConstraint(
            model_name='sessionlog',
            constraint=models.UniqueConstraint(condition=models.Q(('program_session__isnull', False)), fields=('program_session',), name='one_log_per_program_session'),
        ),
        migrations.AddConstraint(
            model_name='sessionlog',
            constraint=models.CheckConstraint(condition=models.Q(('session_rpe__isnull', True), ('session_rpe__range', (1, 10)), _connector='OR'), name='session_rpe_1_to_10'),
        ),
        migrations.AddIndex(
            model_name='sessionexercise',
            index=models.Index(fields=['exercise', 'session_log'], name='session_exercise_by_exercise'),
        ),
        migrations.AddConstraint(
            model_name='checkinanswer',
            constraint=models.UniqueConstraint(fields=('session_log', 'question'), name='one_answer_per_question'),
        ),
        migrations.AddConstraint(
            model_name='setlog',
            constraint=models.UniqueConstraint(fields=('session_exercise', 'set_number'), name='unique_set_per_exercise'),
        ),
        migrations.AddConstraint(
            model_name='setlog',
            constraint=models.CheckConstraint(condition=models.Q(('set_number__gte', 1)), name='set_log_number_from_1'),
        ),
        migrations.AddConstraint(
            model_name='setlog',
            constraint=models.CheckConstraint(condition=models.Q(('load_kg__isnull', True), ('load_kg__gte', 0), _connector='OR'), name='set_log_load_not_negative'),
        ),
    ]
