// Generated by scripts/db-schema.mjs from shared/sync-schema.json. Do not edit: run `npm run db:schema`.
import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

/** The server's schema version (X-Schema-Version) and a hash of the whole description. */
export const SCHEMA_VERSION = 1;
export const SCHEMA_HASH = 'c1ba73c5e88c4a66';

export const bodyweightEntry = sqliteTable('accounts_bodyweightentry', {
  id: text('id').primaryKey(),
  athleteId: text('athlete_id').notNull(),
  date: text('date').notNull(),
  kg: text('kg').notNull(),
  source: text('source').notNull(),
  createdAt: text('created_at').notNull(),
});

export const maxEntry = sqliteTable('accounts_maxentry', {
  id: text('id').primaryKey(),
  athleteId: text('athlete_id').notNull(),
  exerciseId: text('exercise_id').notNull(),
  date: text('date').notNull(),
  kg: text('kg').notNull(),
  reps: integer('reps').notNull(),
  source: text('source').notNull(),
  setLogId: text('set_log_id'),
  createdAt: text('created_at').notNull(),
});

export const coaching = sqliteTable('accounts_coaching', {
  id: text('id').primaryKey(),
  coachId: text('coach_id').notNull(),
  athleteId: text('athlete_id').notNull(),
  gymId: text('gym_id').notNull(),
  status: text('status').notNull(),
  startedAt: text('started_at').notNull(),
  endedAt: text('ended_at'),
});

export const program = sqliteTable('programs_program', {
  id: text('id').primaryKey(),
  athleteId: text('athlete_id').notNull(),
  name: text('name').notNull(),
  startDate: text('start_date').notNull(),
  note: text('note').notNull(),
  active: integer('active', { mode: 'boolean' }).notNull(),
  sourceTemplateId: text('source_template_id'),
  createdById: text('created_by_id'),
  createdAt: text('created_at').notNull(),
  endedAt: text('ended_at'),
});

export const programWeek = sqliteTable('programs_programweek', {
  id: text('id').primaryKey(),
  programId: text('program_id').notNull(),
  athleteId: text('athlete_id').notNull(),
  order: integer('order').notNull(),
  weekTypeId: text('week_type_id').notNull(),
  startDate: text('start_date').notNull(),
  focusNote: text('focus_note').notNull(),
  published: integer('published', { mode: 'boolean' }).notNull(),
  publishedAt: text('published_at'),
});

export const programDay = sqliteTable('programs_programday', {
  id: text('id').primaryKey(),
  weekId: text('week_id').notNull(),
  athleteId: text('athlete_id').notNull(),
  date: text('date').notNull(),
});

export const programSession = sqliteTable('programs_programsession', {
  id: text('id').primaryKey(),
  dayId: text('day_id').notNull(),
  athleteId: text('athlete_id').notNull(),
  order: integer('order').notNull(),
  name: text('name').notNull(),
});

export const prescription = sqliteTable('programs_prescription', {
  id: text('id').primaryKey(),
  sets: integer('sets').notNull(),
  repScheme: text('rep_scheme').notNull(),
  reps: integer('reps'),
  durationSeconds: integer('duration_seconds'),
  loadValue: text('load_value'),
  loadBasis: text('load_basis').notNull(),
  rir: integer('rir'),
  rirMax: integer('rir_max'),
  note: text('note').notNull(),
  customFields: text('custom_fields', { mode: 'json' }).notNull(),
  warmup: integer('warmup', { mode: 'boolean' }).notNull(),
  section: text('section').notNull(),
  sectionNote: text('section_note').notNull(),
  superset: integer('superset', { mode: 'boolean' }).notNull(),
  sessionId: text('session_id').notNull(),
  athleteId: text('athlete_id').notNull(),
  order: integer('order').notNull(),
  exerciseId: text('exercise_id').notNull(),
});

export const prescribedSet = sqliteTable('programs_prescribedset', {
  id: text('id').primaryKey(),
  setNumber: integer('set_number').notNull(),
  repScheme: text('rep_scheme').notNull(),
  reps: integer('reps'),
  loadValue: text('load_value'),
  prescriptionId: text('prescription_id').notNull(),
  athleteId: text('athlete_id').notNull(),
});

export const prescriptionTag = sqliteTable('programs_prescriptiontag', {
  id: text('id').primaryKey(),
  prescriptionId: text('prescription_id').notNull(),
  tagId: text('tag_id').notNull(),
  athleteId: text('athlete_id').notNull(),
});

export const habit = sqliteTable('programs_habit', {
  id: text('id').primaryKey(),
  athleteId: text('athlete_id').notNull(),
  order: integer('order').notNull(),
  name: text('name').notNull(),
  emoji: text('emoji').notNull(),
  cadence: text('cadence').notNull(),
  note: text('note').notNull(),
  sourceTemplateId: text('source_template_id'),
  createdAt: text('created_at').notNull(),
  archivedAt: text('archived_at'),
});

export const habitLog = sqliteTable('programs_habitlog', {
  id: text('id').primaryKey(),
  habitId: text('habit_id').notNull(),
  athleteId: text('athlete_id').notNull(),
  date: text('date').notNull(),
  createdAt: text('created_at').notNull(),
});

export const checkinQuestion = sqliteTable('workouts_checkinquestion', {
  id: text('id').primaryKey(),
  gymId: text('gym_id'),
  athleteId: text('athlete_id'),
  order: integer('order').notNull(),
  type: text('type').notNull(),
  text: text('text').notNull(),
  lowLabel: text('low_label').notNull(),
  highLabel: text('high_label').notNull(),
  options: text('options', { mode: 'json' }).notNull(),
  detailLabel: text('detail_label').notNull(),
  archived: integer('archived', { mode: 'boolean' }).notNull(),
  createdAt: text('created_at').notNull(),
});

export const sessionLog = sqliteTable('workouts_sessionlog', {
  id: text('id').primaryKey(),
  athleteId: text('athlete_id').notNull(),
  programSessionId: text('program_session_id'),
  date: text('date').notNull(),
  name: text('name').notNull(),
  weekTypeId: text('week_type_id'),
  startedAt: text('started_at').notNull(),
  finishedAt: text('finished_at'),
  checkinSkipped: integer('checkin_skipped', { mode: 'boolean' }).notNull(),
  sessionRpe: integer('session_rpe'),
  comment: text('comment').notNull(),
});

export const sessionExercise = sqliteTable('workouts_sessionexercise', {
  id: text('id').primaryKey(),
  sessionLogId: text('session_log_id').notNull(),
  athleteId: text('athlete_id').notNull(),
  prescriptionId: text('prescription_id'),
  exerciseId: text('exercise_id'),
  exerciseName: text('exercise_name').notNull(),
  order: integer('order').notNull(),
  prescribed: text('prescribed', { mode: 'json' }).notNull(),
  warmup: integer('warmup', { mode: 'boolean' }).notNull(),
  checkedAt: text('checked_at'),
});

export const setLog = sqliteTable('workouts_setlog', {
  id: text('id').primaryKey(),
  sessionExerciseId: text('session_exercise_id').notNull(),
  athleteId: text('athlete_id').notNull(),
  setNumber: integer('set_number').notNull(),
  loadKg: text('load_kg'),
  reps: integer('reps'),
  durationSeconds: integer('duration_seconds'),
  rir: integer('rir'),
  done: integer('done', { mode: 'boolean' }).notNull(),
  loggedAt: text('logged_at').notNull(),
  maxDismissed: integer('max_dismissed', { mode: 'boolean' }).notNull(),
});

export const checkinAnswer = sqliteTable('workouts_checkinanswer', {
  id: text('id').primaryKey(),
  sessionLogId: text('session_log_id').notNull(),
  athleteId: text('athlete_id').notNull(),
  questionId: text('question_id'),
  order: integer('order').notNull(),
  questionText: text('question_text').notNull(),
  type: text('type').notNull(),
  value: text('value').notNull(),
  otherText: text('other_text').notNull(),
});

export const issueReport = sqliteTable('workouts_issuereport', {
  id: text('id').primaryKey(),
  athleteId: text('athlete_id').notNull(),
  sessionLogId: text('session_log_id'),
  kind: text('kind').notNull(),
  text: text('text').notNull(),
  createdAt: text('created_at').notNull(),
  resolvedAt: text('resolved_at'),
});

export const formVideo = sqliteTable('workouts_formvideo', {
  id: text('id').primaryKey(),
  sessionLogId: text('session_log_id').notNull(),
  athleteId: text('athlete_id').notNull(),
  sessionExerciseId: text('session_exercise_id'),
  exerciseName: text('exercise_name').notNull(),
  contentType: text('content_type').notNull(),
  size: integer('size').notNull(),
  note: text('note').notNull(),
  createdAt: text('created_at').notNull(),
  uploadedAt: text('uploaded_at'),
  reviewedAt: text('reviewed_at'),
  reviewedById: text('reviewed_by_id'),
  feedback: text('feedback').notNull(),
  deletedAt: text('deleted_at'),
});

export const thread = sqliteTable('messaging_thread', {
  id: text('id').primaryKey(),
  coachingId: text('coaching_id').notNull(),
  athleteId: text('athlete_id').notNull(),
  createdAt: text('created_at').notNull(),
});

export const message = sqliteTable('messaging_message', {
  id: text('id').primaryKey(),
  threadId: text('thread_id').notNull(),
  athleteId: text('athlete_id').notNull(),
  senderId: text('sender_id'),
  body: text('body').notNull(),
  sentAt: text('sent_at').notNull(),
  readAt: text('read_at'),
});

export const category = sqliteTable('exercises_category', {
  id: text('id').primaryKey(),
  gymId: text('gym_id').notNull(),
  name: text('name').notNull(),
  order: integer('order').notNull(),
});

export const tag = sqliteTable('exercises_tag', {
  id: text('id').primaryKey(),
  gymId: text('gym_id').notNull(),
  name: text('name').notNull(),
});

export const exercise = sqliteTable('exercises_exercise', {
  id: text('id').primaryKey(),
  gymId: text('gym_id').notNull(),
  key: text('key').notNull(),
  name: text('name').notNull(),
  categoryId: text('category_id').notNull(),
  measure: text('measure').notNull(),
  repsPerRep: integer('reps_per_rep').notNull(),
  percentOfId: text('percent_of_id'),
  youtubeUrl: text('youtube_url').notNull(),
  cue: text('cue').notNull(),
  warmup: integer('warmup', { mode: 'boolean' }).notNull(),
  archived: integer('archived', { mode: 'boolean' }).notNull(),
});

export const exerciseTag = sqliteTable('exercises_exercisetag', {
  id: text('id').primaryKey(),
  exerciseId: text('exercise_id').notNull(),
  tagId: text('tag_id').notNull(),
  gymId: text('gym_id').notNull(),
});

export const trackedLift = sqliteTable('exercises_trackedlift', {
  id: text('id').primaryKey(),
  gymId: text('gym_id').notNull(),
  exerciseId: text('exercise_id').notNull(),
  order: integer('order').notNull(),
});

export const weekType = sqliteTable('programs_weektype', {
  id: text('id').primaryKey(),
  gymId: text('gym_id').notNull(),
  name: text('name').notNull(),
  description: text('description').notNull(),
  colour: text('colour').notNull(),
  order: integer('order').notNull(),
  archived: integer('archived', { mode: 'boolean' }).notNull(),
});

/** Column types by table, for storing rows as pull sends them. */
export const COLUMNS = {
  accounts_bodyweightentry: { id: 'text', athlete_id: 'text', date: 'text', kg: 'text', source: 'text', created_at: 'text' },
  accounts_maxentry: { id: 'text', athlete_id: 'text', exercise_id: 'text', date: 'text', kg: 'text', reps: 'integer', source: 'text', set_log_id: 'text', created_at: 'text' },
  accounts_coaching: { id: 'text', coach_id: 'text', athlete_id: 'text', gym_id: 'text', status: 'text', started_at: 'text', ended_at: 'text' },
  programs_program: { id: 'text', athlete_id: 'text', name: 'text', start_date: 'text', note: 'text', active: 'boolean', source_template_id: 'text', created_by_id: 'text', created_at: 'text', ended_at: 'text' },
  programs_programweek: { id: 'text', program_id: 'text', athlete_id: 'text', order: 'integer', week_type_id: 'text', start_date: 'text', focus_note: 'text', published: 'boolean', published_at: 'text' },
  programs_programday: { id: 'text', week_id: 'text', athlete_id: 'text', date: 'text' },
  programs_programsession: { id: 'text', day_id: 'text', athlete_id: 'text', order: 'integer', name: 'text' },
  programs_prescription: { id: 'text', sets: 'integer', rep_scheme: 'text', reps: 'integer', duration_seconds: 'integer', load_value: 'text', load_basis: 'text', rir: 'integer', rir_max: 'integer', note: 'text', custom_fields: 'json', warmup: 'boolean', section: 'text', section_note: 'text', superset: 'boolean', session_id: 'text', athlete_id: 'text', order: 'integer', exercise_id: 'text' },
  programs_prescribedset: { id: 'text', set_number: 'integer', rep_scheme: 'text', reps: 'integer', load_value: 'text', prescription_id: 'text', athlete_id: 'text' },
  programs_prescriptiontag: { id: 'text', prescription_id: 'text', tag_id: 'text', athlete_id: 'text' },
  programs_habit: { id: 'text', athlete_id: 'text', order: 'integer', name: 'text', emoji: 'text', cadence: 'text', note: 'text', source_template_id: 'text', created_at: 'text', archived_at: 'text' },
  programs_habitlog: { id: 'text', habit_id: 'text', athlete_id: 'text', date: 'text', created_at: 'text' },
  workouts_checkinquestion: { id: 'text', gym_id: 'text', athlete_id: 'text', order: 'integer', type: 'text', text: 'text', low_label: 'text', high_label: 'text', options: 'json', detail_label: 'text', archived: 'boolean', created_at: 'text' },
  workouts_sessionlog: { id: 'text', athlete_id: 'text', program_session_id: 'text', date: 'text', name: 'text', week_type_id: 'text', started_at: 'text', finished_at: 'text', checkin_skipped: 'boolean', session_rpe: 'integer', comment: 'text' },
  workouts_sessionexercise: { id: 'text', session_log_id: 'text', athlete_id: 'text', prescription_id: 'text', exercise_id: 'text', exercise_name: 'text', order: 'integer', prescribed: 'json', warmup: 'boolean', checked_at: 'text' },
  workouts_setlog: { id: 'text', session_exercise_id: 'text', athlete_id: 'text', set_number: 'integer', load_kg: 'text', reps: 'integer', duration_seconds: 'integer', rir: 'integer', done: 'boolean', logged_at: 'text', max_dismissed: 'boolean' },
  workouts_checkinanswer: { id: 'text', session_log_id: 'text', athlete_id: 'text', question_id: 'text', order: 'integer', question_text: 'text', type: 'text', value: 'text', other_text: 'text' },
  workouts_issuereport: { id: 'text', athlete_id: 'text', session_log_id: 'text', kind: 'text', text: 'text', created_at: 'text', resolved_at: 'text' },
  workouts_formvideo: { id: 'text', session_log_id: 'text', athlete_id: 'text', session_exercise_id: 'text', exercise_name: 'text', content_type: 'text', size: 'integer', note: 'text', created_at: 'text', uploaded_at: 'text', reviewed_at: 'text', reviewed_by_id: 'text', feedback: 'text', deleted_at: 'text' },
  messaging_thread: { id: 'text', coaching_id: 'text', athlete_id: 'text', created_at: 'text' },
  messaging_message: { id: 'text', thread_id: 'text', athlete_id: 'text', sender_id: 'text', body: 'text', sent_at: 'text', read_at: 'text' },
  exercises_category: { id: 'text', gym_id: 'text', name: 'text', order: 'integer' },
  exercises_tag: { id: 'text', gym_id: 'text', name: 'text' },
  exercises_exercise: { id: 'text', gym_id: 'text', key: 'text', name: 'text', category_id: 'text', measure: 'text', reps_per_rep: 'integer', percent_of_id: 'text', youtube_url: 'text', cue: 'text', warmup: 'boolean', archived: 'boolean' },
  exercises_exercisetag: { id: 'text', exercise_id: 'text', tag_id: 'text', gym_id: 'text' },
  exercises_trackedlift: { id: 'text', gym_id: 'text', exercise_id: 'text', order: 'integer' },
  programs_weektype: { id: 'text', gym_id: 'text', name: 'text', description: 'text', colour: 'text', order: 'integer', archived: 'boolean' },
} as const satisfies Record<string, Record<string, 'text' | 'integer' | 'boolean' | 'real' | 'json'>>;

export type SyncedTable = keyof typeof COLUMNS;

/** Which tables hold the athlete's own data and which their gym's library. */
export const SCOPE: Record<SyncedTable, 'athlete' | 'library'> = {
  accounts_bodyweightentry: 'athlete',
  accounts_maxentry: 'athlete',
  accounts_coaching: 'athlete',
  programs_program: 'athlete',
  programs_programweek: 'athlete',
  programs_programday: 'athlete',
  programs_programsession: 'athlete',
  programs_prescription: 'athlete',
  programs_prescribedset: 'athlete',
  programs_prescriptiontag: 'athlete',
  programs_habit: 'athlete',
  programs_habitlog: 'athlete',
  workouts_checkinquestion: 'athlete',
  workouts_sessionlog: 'athlete',
  workouts_sessionexercise: 'athlete',
  workouts_setlog: 'athlete',
  workouts_checkinanswer: 'athlete',
  workouts_issuereport: 'athlete',
  workouts_formvideo: 'athlete',
  messaging_thread: 'athlete',
  messaging_message: 'athlete',
  exercises_category: 'library',
  exercises_tag: 'library',
  exercises_exercise: 'library',
  exercises_exercisetag: 'library',
  exercises_trackedlift: 'library',
  programs_weektype: 'library',
};

/** Creates every synced table and its indexes. */
export const CREATE: readonly string[] = [
  "CREATE TABLE \"accounts_bodyweightentry\" (\"id\" TEXT PRIMARY KEY, \"athlete_id\" TEXT NOT NULL, \"date\" TEXT NOT NULL, \"kg\" TEXT NOT NULL, \"source\" TEXT NOT NULL, \"created_at\" TEXT NOT NULL)",
  "CREATE INDEX \"accounts_bodyweightentry__athlete_id\" ON \"accounts_bodyweightentry\" (\"athlete_id\")",
  "CREATE TABLE \"accounts_maxentry\" (\"id\" TEXT PRIMARY KEY, \"athlete_id\" TEXT NOT NULL, \"exercise_id\" TEXT NOT NULL, \"date\" TEXT NOT NULL, \"kg\" TEXT NOT NULL, \"reps\" INTEGER NOT NULL, \"source\" TEXT NOT NULL, \"set_log_id\" TEXT, \"created_at\" TEXT NOT NULL)",
  "CREATE INDEX \"accounts_maxentry__athlete_id\" ON \"accounts_maxentry\" (\"athlete_id\")",
  "CREATE INDEX \"accounts_maxentry__exercise_id\" ON \"accounts_maxentry\" (\"exercise_id\")",
  "CREATE INDEX \"accounts_maxentry__set_log_id\" ON \"accounts_maxentry\" (\"set_log_id\")",
  "CREATE TABLE \"accounts_coaching\" (\"id\" TEXT PRIMARY KEY, \"coach_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL, \"gym_id\" TEXT NOT NULL, \"status\" TEXT NOT NULL, \"started_at\" TEXT NOT NULL, \"ended_at\" TEXT)",
  "CREATE INDEX \"accounts_coaching__coach_id\" ON \"accounts_coaching\" (\"coach_id\")",
  "CREATE INDEX \"accounts_coaching__athlete_id\" ON \"accounts_coaching\" (\"athlete_id\")",
  "CREATE INDEX \"accounts_coaching__gym_id\" ON \"accounts_coaching\" (\"gym_id\")",
  "CREATE TABLE \"programs_program\" (\"id\" TEXT PRIMARY KEY, \"athlete_id\" TEXT NOT NULL, \"name\" TEXT NOT NULL, \"start_date\" TEXT NOT NULL, \"note\" TEXT NOT NULL, \"active\" INTEGER NOT NULL, \"source_template_id\" TEXT, \"created_by_id\" TEXT, \"created_at\" TEXT NOT NULL, \"ended_at\" TEXT)",
  "CREATE INDEX \"programs_program__athlete_id\" ON \"programs_program\" (\"athlete_id\")",
  "CREATE INDEX \"programs_program__source_template_id\" ON \"programs_program\" (\"source_template_id\")",
  "CREATE INDEX \"programs_program__created_by_id\" ON \"programs_program\" (\"created_by_id\")",
  "CREATE TABLE \"programs_programweek\" (\"id\" TEXT PRIMARY KEY, \"program_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL, \"order\" INTEGER NOT NULL, \"week_type_id\" TEXT NOT NULL, \"start_date\" TEXT NOT NULL, \"focus_note\" TEXT NOT NULL, \"published\" INTEGER NOT NULL, \"published_at\" TEXT)",
  "CREATE INDEX \"programs_programweek__program_id\" ON \"programs_programweek\" (\"program_id\")",
  "CREATE INDEX \"programs_programweek__athlete_id\" ON \"programs_programweek\" (\"athlete_id\")",
  "CREATE INDEX \"programs_programweek__week_type_id\" ON \"programs_programweek\" (\"week_type_id\")",
  "CREATE TABLE \"programs_programday\" (\"id\" TEXT PRIMARY KEY, \"week_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL, \"date\" TEXT NOT NULL)",
  "CREATE INDEX \"programs_programday__week_id\" ON \"programs_programday\" (\"week_id\")",
  "CREATE INDEX \"programs_programday__athlete_id\" ON \"programs_programday\" (\"athlete_id\")",
  "CREATE TABLE \"programs_programsession\" (\"id\" TEXT PRIMARY KEY, \"day_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL, \"order\" INTEGER NOT NULL, \"name\" TEXT NOT NULL)",
  "CREATE INDEX \"programs_programsession__day_id\" ON \"programs_programsession\" (\"day_id\")",
  "CREATE INDEX \"programs_programsession__athlete_id\" ON \"programs_programsession\" (\"athlete_id\")",
  "CREATE TABLE \"programs_prescription\" (\"id\" TEXT PRIMARY KEY, \"sets\" INTEGER NOT NULL, \"rep_scheme\" TEXT NOT NULL, \"reps\" INTEGER, \"duration_seconds\" INTEGER, \"load_value\" TEXT, \"load_basis\" TEXT NOT NULL, \"rir\" INTEGER, \"rir_max\" INTEGER, \"note\" TEXT NOT NULL, \"custom_fields\" TEXT NOT NULL, \"warmup\" INTEGER NOT NULL, \"section\" TEXT NOT NULL, \"section_note\" TEXT NOT NULL, \"superset\" INTEGER NOT NULL, \"session_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL, \"order\" INTEGER NOT NULL, \"exercise_id\" TEXT NOT NULL)",
  "CREATE INDEX \"programs_prescription__session_id\" ON \"programs_prescription\" (\"session_id\")",
  "CREATE INDEX \"programs_prescription__athlete_id\" ON \"programs_prescription\" (\"athlete_id\")",
  "CREATE INDEX \"programs_prescription__exercise_id\" ON \"programs_prescription\" (\"exercise_id\")",
  "CREATE TABLE \"programs_prescribedset\" (\"id\" TEXT PRIMARY KEY, \"set_number\" INTEGER NOT NULL, \"rep_scheme\" TEXT NOT NULL, \"reps\" INTEGER, \"load_value\" TEXT, \"prescription_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL)",
  "CREATE INDEX \"programs_prescribedset__prescription_id\" ON \"programs_prescribedset\" (\"prescription_id\")",
  "CREATE INDEX \"programs_prescribedset__athlete_id\" ON \"programs_prescribedset\" (\"athlete_id\")",
  "CREATE TABLE \"programs_prescriptiontag\" (\"id\" TEXT PRIMARY KEY, \"prescription_id\" TEXT NOT NULL, \"tag_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL)",
  "CREATE INDEX \"programs_prescriptiontag__prescription_id\" ON \"programs_prescriptiontag\" (\"prescription_id\")",
  "CREATE INDEX \"programs_prescriptiontag__tag_id\" ON \"programs_prescriptiontag\" (\"tag_id\")",
  "CREATE INDEX \"programs_prescriptiontag__athlete_id\" ON \"programs_prescriptiontag\" (\"athlete_id\")",
  "CREATE TABLE \"programs_habit\" (\"id\" TEXT PRIMARY KEY, \"athlete_id\" TEXT NOT NULL, \"order\" INTEGER NOT NULL, \"name\" TEXT NOT NULL, \"emoji\" TEXT NOT NULL, \"cadence\" TEXT NOT NULL, \"note\" TEXT NOT NULL, \"source_template_id\" TEXT, \"created_at\" TEXT NOT NULL, \"archived_at\" TEXT)",
  "CREATE INDEX \"programs_habit__athlete_id\" ON \"programs_habit\" (\"athlete_id\")",
  "CREATE INDEX \"programs_habit__source_template_id\" ON \"programs_habit\" (\"source_template_id\")",
  "CREATE TABLE \"programs_habitlog\" (\"id\" TEXT PRIMARY KEY, \"habit_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL, \"date\" TEXT NOT NULL, \"created_at\" TEXT NOT NULL)",
  "CREATE INDEX \"programs_habitlog__habit_id\" ON \"programs_habitlog\" (\"habit_id\")",
  "CREATE INDEX \"programs_habitlog__athlete_id\" ON \"programs_habitlog\" (\"athlete_id\")",
  "CREATE TABLE \"workouts_checkinquestion\" (\"id\" TEXT PRIMARY KEY, \"gym_id\" TEXT, \"athlete_id\" TEXT, \"order\" INTEGER NOT NULL, \"type\" TEXT NOT NULL, \"text\" TEXT NOT NULL, \"low_label\" TEXT NOT NULL, \"high_label\" TEXT NOT NULL, \"options\" TEXT NOT NULL, \"detail_label\" TEXT NOT NULL, \"archived\" INTEGER NOT NULL, \"created_at\" TEXT NOT NULL)",
  "CREATE INDEX \"workouts_checkinquestion__gym_id\" ON \"workouts_checkinquestion\" (\"gym_id\")",
  "CREATE INDEX \"workouts_checkinquestion__athlete_id\" ON \"workouts_checkinquestion\" (\"athlete_id\")",
  "CREATE TABLE \"workouts_sessionlog\" (\"id\" TEXT PRIMARY KEY, \"athlete_id\" TEXT NOT NULL, \"program_session_id\" TEXT, \"date\" TEXT NOT NULL, \"name\" TEXT NOT NULL, \"week_type_id\" TEXT, \"started_at\" TEXT NOT NULL, \"finished_at\" TEXT, \"checkin_skipped\" INTEGER NOT NULL, \"session_rpe\" INTEGER, \"comment\" TEXT NOT NULL)",
  "CREATE INDEX \"workouts_sessionlog__athlete_id\" ON \"workouts_sessionlog\" (\"athlete_id\")",
  "CREATE INDEX \"workouts_sessionlog__program_session_id\" ON \"workouts_sessionlog\" (\"program_session_id\")",
  "CREATE INDEX \"workouts_sessionlog__week_type_id\" ON \"workouts_sessionlog\" (\"week_type_id\")",
  "CREATE TABLE \"workouts_sessionexercise\" (\"id\" TEXT PRIMARY KEY, \"session_log_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL, \"prescription_id\" TEXT, \"exercise_id\" TEXT, \"exercise_name\" TEXT NOT NULL, \"order\" INTEGER NOT NULL, \"prescribed\" TEXT NOT NULL, \"warmup\" INTEGER NOT NULL, \"checked_at\" TEXT)",
  "CREATE INDEX \"workouts_sessionexercise__session_log_id\" ON \"workouts_sessionexercise\" (\"session_log_id\")",
  "CREATE INDEX \"workouts_sessionexercise__athlete_id\" ON \"workouts_sessionexercise\" (\"athlete_id\")",
  "CREATE INDEX \"workouts_sessionexercise__prescription_id\" ON \"workouts_sessionexercise\" (\"prescription_id\")",
  "CREATE INDEX \"workouts_sessionexercise__exercise_id\" ON \"workouts_sessionexercise\" (\"exercise_id\")",
  "CREATE TABLE \"workouts_setlog\" (\"id\" TEXT PRIMARY KEY, \"session_exercise_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL, \"set_number\" INTEGER NOT NULL, \"load_kg\" TEXT, \"reps\" INTEGER, \"duration_seconds\" INTEGER, \"rir\" INTEGER, \"done\" INTEGER NOT NULL, \"logged_at\" TEXT NOT NULL, \"max_dismissed\" INTEGER NOT NULL)",
  "CREATE INDEX \"workouts_setlog__session_exercise_id\" ON \"workouts_setlog\" (\"session_exercise_id\")",
  "CREATE INDEX \"workouts_setlog__athlete_id\" ON \"workouts_setlog\" (\"athlete_id\")",
  "CREATE TABLE \"workouts_checkinanswer\" (\"id\" TEXT PRIMARY KEY, \"session_log_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL, \"question_id\" TEXT, \"order\" INTEGER NOT NULL, \"question_text\" TEXT NOT NULL, \"type\" TEXT NOT NULL, \"value\" TEXT NOT NULL, \"other_text\" TEXT NOT NULL)",
  "CREATE INDEX \"workouts_checkinanswer__session_log_id\" ON \"workouts_checkinanswer\" (\"session_log_id\")",
  "CREATE INDEX \"workouts_checkinanswer__athlete_id\" ON \"workouts_checkinanswer\" (\"athlete_id\")",
  "CREATE INDEX \"workouts_checkinanswer__question_id\" ON \"workouts_checkinanswer\" (\"question_id\")",
  "CREATE TABLE \"workouts_issuereport\" (\"id\" TEXT PRIMARY KEY, \"athlete_id\" TEXT NOT NULL, \"session_log_id\" TEXT, \"kind\" TEXT NOT NULL, \"text\" TEXT NOT NULL, \"created_at\" TEXT NOT NULL, \"resolved_at\" TEXT)",
  "CREATE INDEX \"workouts_issuereport__athlete_id\" ON \"workouts_issuereport\" (\"athlete_id\")",
  "CREATE INDEX \"workouts_issuereport__session_log_id\" ON \"workouts_issuereport\" (\"session_log_id\")",
  "CREATE TABLE \"workouts_formvideo\" (\"id\" TEXT PRIMARY KEY, \"session_log_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL, \"session_exercise_id\" TEXT, \"exercise_name\" TEXT NOT NULL, \"content_type\" TEXT NOT NULL, \"size\" INTEGER NOT NULL, \"note\" TEXT NOT NULL, \"created_at\" TEXT NOT NULL, \"uploaded_at\" TEXT, \"reviewed_at\" TEXT, \"reviewed_by_id\" TEXT, \"feedback\" TEXT NOT NULL, \"deleted_at\" TEXT)",
  "CREATE INDEX \"workouts_formvideo__session_log_id\" ON \"workouts_formvideo\" (\"session_log_id\")",
  "CREATE INDEX \"workouts_formvideo__athlete_id\" ON \"workouts_formvideo\" (\"athlete_id\")",
  "CREATE INDEX \"workouts_formvideo__session_exercise_id\" ON \"workouts_formvideo\" (\"session_exercise_id\")",
  "CREATE INDEX \"workouts_formvideo__reviewed_by_id\" ON \"workouts_formvideo\" (\"reviewed_by_id\")",
  "CREATE TABLE \"messaging_thread\" (\"id\" TEXT PRIMARY KEY, \"coaching_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL, \"created_at\" TEXT NOT NULL)",
  "CREATE INDEX \"messaging_thread__coaching_id\" ON \"messaging_thread\" (\"coaching_id\")",
  "CREATE INDEX \"messaging_thread__athlete_id\" ON \"messaging_thread\" (\"athlete_id\")",
  "CREATE TABLE \"messaging_message\" (\"id\" TEXT PRIMARY KEY, \"thread_id\" TEXT NOT NULL, \"athlete_id\" TEXT NOT NULL, \"sender_id\" TEXT, \"body\" TEXT NOT NULL, \"sent_at\" TEXT NOT NULL, \"read_at\" TEXT)",
  "CREATE INDEX \"messaging_message__thread_id\" ON \"messaging_message\" (\"thread_id\")",
  "CREATE INDEX \"messaging_message__athlete_id\" ON \"messaging_message\" (\"athlete_id\")",
  "CREATE INDEX \"messaging_message__sender_id\" ON \"messaging_message\" (\"sender_id\")",
  "CREATE TABLE \"exercises_category\" (\"id\" TEXT PRIMARY KEY, \"gym_id\" TEXT NOT NULL, \"name\" TEXT NOT NULL, \"order\" INTEGER NOT NULL)",
  "CREATE INDEX \"exercises_category__gym_id\" ON \"exercises_category\" (\"gym_id\")",
  "CREATE TABLE \"exercises_tag\" (\"id\" TEXT PRIMARY KEY, \"gym_id\" TEXT NOT NULL, \"name\" TEXT NOT NULL)",
  "CREATE INDEX \"exercises_tag__gym_id\" ON \"exercises_tag\" (\"gym_id\")",
  "CREATE TABLE \"exercises_exercise\" (\"id\" TEXT PRIMARY KEY, \"gym_id\" TEXT NOT NULL, \"key\" TEXT NOT NULL, \"name\" TEXT NOT NULL, \"category_id\" TEXT NOT NULL, \"measure\" TEXT NOT NULL, \"reps_per_rep\" INTEGER NOT NULL, \"percent_of_id\" TEXT, \"youtube_url\" TEXT NOT NULL, \"cue\" TEXT NOT NULL, \"warmup\" INTEGER NOT NULL, \"archived\" INTEGER NOT NULL)",
  "CREATE INDEX \"exercises_exercise__gym_id\" ON \"exercises_exercise\" (\"gym_id\")",
  "CREATE INDEX \"exercises_exercise__category_id\" ON \"exercises_exercise\" (\"category_id\")",
  "CREATE INDEX \"exercises_exercise__percent_of_id\" ON \"exercises_exercise\" (\"percent_of_id\")",
  "CREATE TABLE \"exercises_exercisetag\" (\"id\" TEXT PRIMARY KEY, \"exercise_id\" TEXT NOT NULL, \"tag_id\" TEXT NOT NULL, \"gym_id\" TEXT NOT NULL)",
  "CREATE INDEX \"exercises_exercisetag__exercise_id\" ON \"exercises_exercisetag\" (\"exercise_id\")",
  "CREATE INDEX \"exercises_exercisetag__tag_id\" ON \"exercises_exercisetag\" (\"tag_id\")",
  "CREATE INDEX \"exercises_exercisetag__gym_id\" ON \"exercises_exercisetag\" (\"gym_id\")",
  "CREATE TABLE \"exercises_trackedlift\" (\"id\" TEXT PRIMARY KEY, \"gym_id\" TEXT NOT NULL, \"exercise_id\" TEXT NOT NULL, \"order\" INTEGER NOT NULL)",
  "CREATE INDEX \"exercises_trackedlift__gym_id\" ON \"exercises_trackedlift\" (\"gym_id\")",
  "CREATE INDEX \"exercises_trackedlift__exercise_id\" ON \"exercises_trackedlift\" (\"exercise_id\")",
  "CREATE TABLE \"programs_weektype\" (\"id\" TEXT PRIMARY KEY, \"gym_id\" TEXT NOT NULL, \"name\" TEXT NOT NULL, \"description\" TEXT NOT NULL, \"colour\" TEXT NOT NULL, \"order\" INTEGER NOT NULL, \"archived\" INTEGER NOT NULL)",
  "CREATE INDEX \"programs_weektype__gym_id\" ON \"programs_weektype\" (\"gym_id\")",
];
