// Generates src/db/schema.generated.ts from shared/sync-schema.json (the server's
// `manage.py sync_schema`): a Drizzle table per synced table, the column types the sync
// engine needs to store pulled rows, and the SQL that creates them.
// Run: npm run db:schema. CI fails when the output is stale.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(here, '../../shared/sync-schema.json'), 'utf8');
const schema = JSON.parse(source);
const out = join(here, '../src/db/schema.generated.ts');

const camel = (name) => name.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
const lowerFirst = (name) => name[0].toLowerCase() + name.slice(1);
const SQL_TYPE = { text: 'TEXT', integer: 'INTEGER', boolean: 'INTEGER', real: 'REAL', json: 'TEXT' };

function drizzleColumn(column) {
  const builder = {
    text: `text('${column.name}')`,
    integer: `integer('${column.name}')`,
    boolean: `integer('${column.name}', { mode: 'boolean' })`,
    real: `real('${column.name}')`,
    json: `text('${column.name}', { mode: 'json' })`,
  }[column.type];
  if (!builder) throw new Error(`${column.name}: unknown type ${column.type}`);
  if (column.name === 'id') return `${builder}.primaryKey()`;
  return column.nullable ? builder : `${builder}.notNull()`;
}

function createSql(table) {
  const columns = table.columns.map((c) => {
    const parts = [`"${c.name}"`, SQL_TYPE[c.type]];
    if (c.name === 'id') parts.push('PRIMARY KEY');
    else if (!c.nullable) parts.push('NOT NULL');
    return parts.join(' ');
  });
  const statements = [`CREATE TABLE "${table.name}" (${columns.join(', ')})`];
  for (const c of table.columns.filter((c) => c.index)) {
    statements.push(`CREATE INDEX "${table.name}__${c.name}" ON "${table.name}" ("${c.name}")`);
  }
  return statements;
}

const names = new Set();
const lines = [
  '// Generated by scripts/db-schema.mjs from shared/sync-schema.json. Do not edit: run `npm run db:schema`.',
  'IMPORT',
  '',
  '/** The server\'s schema version (X-Schema-Version) and a hash of the whole description. */',
  `export const SCHEMA_VERSION = ${schema.version};`,
  `export const SCHEMA_HASH = '${createHash('sha256').update(source).digest('hex').slice(0, 16)}';`,
  '',
];

for (const table of schema.tables) {
  const name = lowerFirst(table.model);
  if (names.has(name)) throw new Error(`two synced tables are called ${name}`);
  names.add(name);
  lines.push(`export const ${name} = sqliteTable('${table.name}', {`);
  for (const column of table.columns) lines.push(`  ${camel(column.name)}: ${drizzleColumn(column)},`);
  lines.push('});', '');
}

const typeOf = (table) =>
  `{ ${table.columns.map((c) => `${c.name}: '${c.type}'`).join(', ')} }`;
lines.push(
  '/** Column types by table, for storing rows as pull sends them. */',
  'export const COLUMNS = {',
  ...schema.tables.map((t) => `  ${t.name}: ${typeOf(t)},`),
  "} as const satisfies Record<string, Record<string, 'text' | 'integer' | 'boolean' | 'real' | 'json'>>;",
  '',
  'export type SyncedTable = keyof typeof COLUMNS;',
  '',
  "/** Which tables hold the athlete's own data and which their gym's library. */",
  'export const SCOPE: Record<SyncedTable, \'athlete\' | \'library\'> = {',
  ...schema.tables.map((t) => `  ${t.name}: '${t.scope}',`),
  '};',
  '',
  '/** Creates every synced table and its indexes. */',
  'export const CREATE: readonly string[] = [',
  ...schema.tables.flatMap(createSql).map((sql) => `  ${JSON.stringify(sql)},`),
  '];',
  '',
);

const BUILDER = { text: 'text', json: 'text', integer: 'integer', boolean: 'integer', real: 'real' };
const used = [...new Set(schema.tables.flatMap((t) => t.columns.map((c) => BUILDER[c.type])))];
lines[lines.indexOf('IMPORT')] = `import { ${[...used, 'sqliteTable'].sort().join(', ')} } from 'drizzle-orm/sqlite-core';`;
writeFileSync(out, lines.join('\n'));
console.log(`wrote ${out.split('/app/')[1] ?? out}: ${schema.tables.length} tables`);
